title: ProductMatchingApiResponse
type: object
allOf:
  - $ref: ../common/api/ApiResult.v1.yaml
  - type: object
    properties:
      requestDetails:
        $ref: ./RequestDetails.v1.yaml
      result:
        $ref: ./ProductMatchingResponse.v1.yaml
