title: ProductMatchingMarketsRequest
description: The market to retrieve results for.
type: string
enum:
  - AMAZON_US
  - AMAZON_CA
  - AMAZON_BR
  - AMAZON_MX
  - AMAZON_UK
  - AMAZON_DE
  - AMAZON_FR
  - AMAZON_ES
  - AMAZON_IT
  - AMAZON_AU
  - AMAZON_TR
  - AMAZON_NL
  - AMAZON_PL
  - EBAY_US
  - EBAY_GB
  - EBAY_DE
  - EBAY_ENCA
  - EBAY_AU
  - EBAY_AT
  - EBAY_CH
  - EBAY_ES
  - EBAY_FR
  - EBAY_FRBE
  - EBAY_NLBE
  - EBAY_FRCA
  - EBAY_HK
  - EBAY_IE
  - EBAY_IT
  - EBAY_MY
  - EBAY_NL
  - EBAY_PH
  - EBAY_PL
  - EBAY_SG
  - WALMART_US
example: AMAZON_US