title: ProductAnalysisResponse
allOf:
  - $ref: ../common/api/ApiResult.v1.yaml
  - type: object
    properties:
      requestDetails:
        $ref: ./RequestDetails.v1.yaml
      result:
        $ref: ./ItemOffers.v1.yaml