title: ProductsCollectionReportStatusResponse
type: object
allOf:
  - $ref: ../common/api/ApiResult.v1.yaml
  - type: object
    properties:
      result:
        $ref: ./ProductsCollectionReportStatusResult.v1.yaml