title: ProductDetailsV2Category
type: object
properties:
  name:
    type: string
    description: "The name of the category"
  id:
    type: string
    description: "The id of the category"
  ancestors:
    type: array
    items:
      title: ProductDetailsV2CategoryAncestors
      type: object
      properties:
        id:
          type: string
        name:
          type: string
  channelData:
    $ref: ./ProductDetailsV2CategoryChannelData.v1.yaml
