openapi: 3.0.0
info:
  title: Brands API
  description: 'Brands API provides Algopix brands names, ids and sub brands, by identifying specified brands.'
  termsOfService: 'https://algopix.com/policies'
  contact:
    name: Algopix Support
    email: support@algopix.com
  version: '2.0'
servers:
  - url: 'https://api.algopix.com'
    description: Algopix API
tags:
  - name: Brands endpoints
paths:
  /v4/brands:
    get:
      description: 'This is a synchronous API endpoint. This endpoint retrieves brand names, ids and sub brands for the specified brand name.<br>[**Don''t miss our schemas**](/docs/Making-a-request/Our-schemas.md)'
      tags:
        - Brands endpoints
      summary: Get Brands by brand name
      operationId: get-brands-by-name
      parameters:
        - name: brandName
          in: query
          required: false
          explode: false
          description: The name of the brand.
          schema:
            type: string
      responses:
        '200':
          description: Success - request submitted.</br>**Notice - our examples were generate with mock data**
          content:
            application/json:
              schema:
                $ref: ../models/brands/BrandsResponse.v1.yaml
              examples:
                Response Example:
                  value:
                    timestamp: 1628507562
                    status: SUCCESS
                    statusCode: 200
                    requestId: 28ce74bc-3b34-4166-9441-15b643993a2e
                    result:
                      brands:
                        - name: Plutus Brands
                          id: Zmbdy2v1oa
                          marketNames:
                            - plutus brands
                          subBrands:
                            - null
        '400':
          $ref: '../models/common/responses/statuscode400.v1.yaml'
        '401':
          $ref: '../models/common/responses/statuscode401.v1.yaml'
        '403':
          $ref: '../models/common/responses/statuscode403.v1.yaml'
        '429':
          $ref: '../models/common/responses/statuscode429.v1.yaml'
        '500':
          $ref: '../models/common/responses/statuscode500.v1.yaml'
      security:
        - apiKey: []
          appId: []
  '/v4/brands/{brandId}':
    get:
      description: 'This is a synchronous API endpoint. This endpoint retrieves Algopix name, and sub brands for the specified brandId.<br>[**Don''t miss our schemas**](/docs/Making-a-request/Our-schemas.md)'
      tags:
        - Brands endpoints
      summary: Get Brand by brand id
      operationId: get-brand-by-id
      parameters:
        - name: brandId
          in: path
          description: 'Algopix unique Brand Id [(see "Get Brands by brand name" endpoint)](../~1v4~1brands/get).'
          required: true
          explode: false
          schema:
            type: string
      responses:
        '200':
          description: Success - request submitted.</br>**Notice - our examples were generate with mock data**
          content:
            application/json:
              schema:
                $ref: ../models/brands/BrandsResponse.v1.yaml
              examples:
                Response Example:
                  value:
                    timestamp: 1628507562
                    status: SUCCESS
                    statusCode: 200
                    requestId: 28ce74bc-3b34-4166-9441-15b643993a2e
                    result:
                      brands:
                        - name: Plutus Brands
                          id: Zmbdy2v1oa
                          marketNames:
                            - plutus brands
                          subBrands:
                            - null
        '400':
          $ref: '../models/common/responses/statuscode400.v1.yaml'
        '401':
          $ref: '../models/common/responses/statuscode401.v1.yaml'
        '403':
          $ref: '../models/common/responses/statuscode403.v1.yaml'
        '429':
          $ref: '../models/common/responses/statuscode429.v1.yaml'
        '500':
          $ref: '../models/common/responses/statuscode500.v1.yaml'
      security:
        - apiKey: []
          appId: []
components:
  securitySchemes:
    apiKey:
      type: apiKey
      name: X-API-KEY
      in: header
      description: 'Read our [Authentication](/docs/Making-a-request/Authentication.md) article'
    appId:
      type: apiKey
      name: X-APP-ID
      in: header